In [15]:
import json
import pandas as pd
import matplotlib.pyplot as plt

In [16]:
val_metrics = json.load(open('../model/model_output/validation_metrics.json', 'r'))

# classification_report
filtered = {
    cls: stats
    for cls, stats in val_metrics['classification_report'].items()
    if isinstance(stats, dict)
}
val_classes = (
    pd.DataFrame.from_dict(filtered, orient='index')
      .reset_index()
      .rename(columns={'index': 'class'})
)

# numeric_metrics/overall metrics
val_overall = (
    pd.DataFrame.from_dict(
        val_metrics['numeric_metrics'],
        orient='index',
        columns=['value']
    )
    .reset_index()
    .rename(columns={'index': 'metric'})
)

In [17]:
val_classes

,class,precision,recall,f1-score,support
0,Bradykinin-related peptide family,0.333333,1.000000,0.500000,2.0
1,CRISP family,0.375000,1.000000,0.545455,3.0
2,Cationic peptide family,0.333333,0.875000,0.482759,8.0
3,Conotoxin family,0.633540,0.902655,0.744526,113.0
4,Disintegrin family,1.000000,0.750000,0.857143,4.0
5,FARP (FMRFamide related peptide) family,0.111111,0.500000,0.181818,2.0
6,Flavin monoamine oxidase family,0.500000,1.000000,0.666667,2.0
7,Formicidae venom family,0.294118,1.000000,0.454545,5.0
8,Insulin family,0.200000,1.000000,0.333333,2.0
9,Limacoditoxin family,0.000000,0.000000,0.000000,2.0
10,Long (3 C-C) scorpion toxin superfamily,1.000000,0.800000,0.888889,5.0
11,Long (4 C-C) scorpion toxin superfamily,0.964286,0.964286,0.964286,28.0
12,Long chain scorpion toxin family,0.666667,1.000000,0.800000,4.0
13,MCD family,0.230769,1.000000,0.375000,9.0
14,"Natriuretic, Bradykinin potentiating peptide f...",0.391304,0.900000,0.545455,10.0
15,Neurotoxin family,0.875000,0.933333,0.903226,60.0
16,Non-disulfide-bridged peptide (NDBP) superfamily,0.176471,0.750000,0.285714,4.0
17,PDGF/VEGF growth factor family,0.250000,1.000000,0.400000,1.0
18,Peptidase S1 family,0.317073,1.000000,0.481481,13.0
19,Phospholipase family,0.553191,1.000000,0.712329,26.0
20,Scoloptoxin family,0.147368,0.777778,0.247788,18.0
21,Short scorpion toxin superfamily,0.806452,1.000000,0.892857,25.0
22,Snaclec family,0.777778,1.000000,0.875000,14.0
23,Teretoxin family,0.142857,0.500000,0.222222,2.0
24,Three-finger toxin family,0.837209,1.000000,0.911392,36.0
25,Vasopressin/oxytocin family,0.166667,1.000000,0.285714,1.0
26,Venom Kunitz-type family,0.368421,1.000000,0.538462,7.0
27,Venom metalloproteinase (M12B) family,0.703704,1.000000,0.826087,19.0
28,nontox,0.998947,0.938056,0.967544,8088.0
29,other,0.054945,0.312500,0.093458,32.0
30,macro avg,0.473651,0.863454,0.566105,8545.0
31,weighted avg,0.978027,0.935401,0.952980,8545.0

In [20]:
val_overall

                 metric     value
0   Validation_Accuracy  0.935401
1        Validation_MCC  0.635839
2   Validation_Avg_Loss  0.224854
3  Validation_Micro_MCC  0.933173